### ISSUE TITLE
[REQUEST] - Add possiblity to separate between mouse glyphs and keyboard glyphs

### ISSUE THREAD

**Issue by liitlelenim** [Orange-Panda/Rewired-Glyphs#4]
**Is your feature request related to a problem? Please describe.**
I want to use glyphs in the context of keybindings remapping and the lack of distinction between mouse and keyboard glyphs is a problem.

**Describe the solution you'd like**
I think adding methods GetMouseGlyph and GetKeyboardGlyph in addition to the existing options would make InputGlyphs API much more flexible in terms of further extension.

Edit:
I think this could be also solved by exposing InputGlyphs.GetGlyphFromHardwareMap to the public API.

**Comment by Orange-Panda** [comment]
Taking a look at this now

**Comment by Orange-Panda** [comment]
I have uploaded a new release `v1.2.0` that addresses this issue.

You can use the `InputGlyphs.GetMouseGlyph` and `InputGlyphs.GetKeyboardGlyph` functions. Beware: that these methods will return the `Unbound` glyph if there is no action for that device.

I also took your feedback and exposed `GetGlyphFromHardwareMap` and related functions to the public api. It has been renamed to `GetNativeGlyphFromHardwareMap` to differentiate it from the other glyph functions. I would recommend using the non-native functions in most cases since they return always return glyphs instead of `null`. That being said the native glyph functions are available too if they are of use for your application.
