### ISSUE TITLE
Getting this for every glyph. <sprite="missing-glyphs" name="missing-glyphs_0">

### ISSUE THREAD

**Issue by jibrangillani11** [Orange-Panda/Rewired-Glyphs#9]
I have followed the instruction mentioned on your page to add the package. Set up everything but while testing. I keep getting a missing sprite image for every glyph.

**Comment by Orange-Panda** [comment]
The output you are receiving is the result of the InputGlyph system being unable to determine the input action to represent. This likely due to there not being a Rewired input manager present or the action name or id does not exist on the input manager.

- What is the glyph tag being used before entering play mode?
- Is a rewired input manager present?
- What version of the Rewired Glyphs package do you have installed?

**Comment by jibrangillani11** [comment]
Yes. Rewired is present and working fine for a while now. I even added the controller data files to the individual maps. To test the built in components I just added a TMP text box on the screen. added the formatter script to it and tried different tags like you have mentioned in the guide. When i play the scene all i get is "X" image in the text box for every tag. I am using version 1.5.0(latest). If I am not wrong for tag <glyph "B"> it should display the B key. Or is there something I am missing here?

**Comment by Orange-Panda** [comment]
I believe you may have misunderstood what is supposed to go into the glyph tag. You should place either the `Action Id` or `Name` of the action instead of the name of the controller button. By putting the name of the action instead of the button we can dynamically change the icon if the button for that action changes due to the map changing or if the user switches input device.

![Example of Rewired Manager for an action "Jump" with action id of 2](https://github.com/Orange-Panda/Rewired-Glyphs/assets/32971863/7887b72b-edbd-497d-beb8-d5d6aacf23fc)

For example: if we want to represent the above action we would do `<glyph 2>` or `<glyph Jump>` (`<glyph "Jump">` is also valid).

In this case we can expect this glyph tag to be replaced with an image representing button we have mapped to jump (conventionally the "A" button of an Xbox controller or Space for a keyboard)

> [!CAUTION]
> As of `1.5.0` if your action name contains a space it can't be used in a glyph tag. This is a bug and is targeted to be fixed in a future version. If your action's name does contain a space you must use the action id instead.

**Comment by jibrangillani11** [comment]
Oh ok. Thank you for the clarification.
